name: Postman Collection Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * # 8 am IST Everyday
    - cron: 00 14 * * * # 730 pm IST Everyday
    - cron: 00 06 * * * # 1130 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ec2-github-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.1
      - name: Install Node js again
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '22'
      - name: Install Newman and Html extra globally
        run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
      - name: Run the Postman Collection with Newman
        run: |
              newman run 'Inwarranty-flow Collection Test Copy.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra \
              --reporter-htmlextra-export ./newman/index.html
      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html
      - name: Creating Github Page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: newman/

      - name: Send email notifications
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: Poenix Inwarranty flow test notifications
          to: dhakla.monika@gmail.com
          from: ${{ secrets.EMAIL_USERNAME}}
          body: |
                Hello
                Please find attached html report generated after running collection through GitHub actions.
                is: https://rsmonika.github.io/Phoenix-Inwarranty-Flow/          
          
  


          
        

      

      
